language: r
cache: packages
sudo: false
env:
  global:
  - secure: JLV5jGBNBu3ytzM1FgF+kpEFg/6uQslPu3ABJ+ku5J3sVtG84WuM0w0OaLYVOAaOge0HifUJDCih+kZMWVFP1gQLMukyLrFpwThetNMgGuUtxpAUsUnbFX+ymbngmU+UishoIwno94DOCQ6+kADaCafUFl4qe0n9BKOO66DibDlyxJuZohcyBGt51VhWbHZr1ai84REDXtiQw74O1bmziVW8bkUgsc5xG8Q9/Mpcm4yMNV5sIsZzBXLz4hK5VP8JCbyIOuDaEjtvHSrLhvntzB08AXiddyWLOSEGTMmCul/8bmgtxEo7wkR0bTmJ97CvnqGozeU/VdrB9DabBNZ2BnE0dSohXUD6vJghXTy1EIvszKlLtLVfxMFU4xbpEj+nV+mrJM1x1C7a2omgMSzrDqc56Atbzyzjzk5zxjSVtmhOz7mX3HI6Bf8zIZWnk+dRgHQ4dL+fHqFKkYQLcM7Gd+qIAAPOSW8AsQrGjsWXbHEylaNxqIcEkSTJVJr79Aii0zsr7xhJLnrHOr1XjP3RbvPPkxYPUfgeMk2m6AFSvgRNRwF2DC912vclQXviK0u9T3iM8I2zQlVx9gRh52hV86jpNMoQTMREc/nlMM+AQtOrcRSywYne7EV9MHDwftfn5w4sR/DJ6AtL6b08eYG51DxcBp4F/X+kzENwmgUEiOE=
before_script:
- chmod +x ./_build.sh
- chmod +x ./_deploy.sh
script:
- "./_build.sh"
after_success:
- test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && bash _deploy.sh
